apiVersion: v1
kind: Secret
metadata:
  name: fullstack-secrets
  namespace: fullstack-app
type: Opaque
data:
  # Los valores están codificados en base64
  # Para generar: echo -n "valor" | base64
  SECRET_KEY: ZGphbmdvLWluc2VjdXJlLWNoYW5nZS10aGlzLWluLXByb2R1Y3Rpb24=  # django-insecure-change-this-in-production
  DB_PASSWORD: cGFzc3dvcmQ=  # password
  DJANGO_SUPERUSER_PASSWORD: YWRtaW4xMjM=  # admin123
